INSERT INTO game(id,category) VALUES ('1','balance');
INSERT INTO game(id,category) VALUES ('2','balance');
INSERT INTO game(id,category) VALUES ('3','balance');
INSERT INTO game(id,category) VALUES ('4','balance');
INSERT INTO game(id,category) VALUES ('5','balance');
INSERT INTO game(id,category) VALUES ('6','balance');
INSERT INTO game(id,category) VALUES ('7','balance');
INSERT INTO game(id,category) VALUES ('8','balance');
INSERT INTO game(id,category) VALUES ('9','balance');
INSERT INTO game(id,category) VALUES ('10','balance');
INSERT INTO game(id,category) VALUES ('11','balance');
INSERT INTO game(id,category) VALUES ('12','balance');
INSERT INTO game(id,category) VALUES ('13','balance');
INSERT INTO game(id,category) VALUES ('14','balance');
INSERT INTO game(id,category) VALUES ('15','balance');
INSERT INTO game(id,category) VALUES ('16','balance');
INSERT INTO game(id,category) VALUES ('17','balance');
INSERT INTO game(id,category) VALUES ('18','balance');
INSERT INTO game(id,category) VALUES ('19','balance');

INSERT INTO balance_game(id,solution1,solution2) VALUES (1, '오이케이크 먹기', '김치케이크 먹기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (2, '평생 양치 안하기', '평생 샤워 안하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (3, '요플레 뚜껑 그냥 버리기', '쭈쭈바 꼬다리 그냥 버리기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (4, '365일 폭염', '365일 장마');
INSERT INTO balance_game(id,solution1,solution2) VALUES (5, '평생동안 키 100cm', '평생동안 몸무게 100kg');
INSERT INTO balance_game(id,solution1,solution2) VALUES (6, '100%확률로 500만원', '1/5확률로 100억');
INSERT INTO balance_game(id,solution1,solution2) VALUES (7, '평생 두통', '평생 치통');
INSERT INTO balance_game(id,solution1,solution2) VALUES (8, '온 세상 사람들이 나한테만 말하기', '온 세상 사람들이 나한테 말 안 걸고 내가 말해도 못 듣기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (9, '절친이 애인 새우 까주기', '애인이 절친 새우 까주기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (10, '내가 10억 받고 원수는 100억 받기', '그냥 둘 다 아무것도 안 받기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (11, '내 인터넷 기록 공개하기', '내 카톡, DM기록 공개하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (12, '원하는 음식 평생 무료로 제공받기', '원하는 옷 평생 무료로 제공받기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (13, '언제 죽을지 알기', '어떻게 죽을지 알기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (14, '하루 종일 입 다물고 있기', '하루 종일 말하고 다니기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (15, '300억 받고 모든 인간관계 정리하기', '그냥 살기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (16, '평생 고기 끊기', '평생 밀가루 끊기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (17, '자도 자도 피곤하기', '먹어도 먹어도 배고프기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (18, '마마보이/마마걸이랑 결혼하기', '바람둥이랑 결혼하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (19, '이국종 교수한테 맞고 추성훈한테 수술 받기', '추성훈한테 맞고 이국종 교수한테 수술 받기');

INSERT INTO game(id,category) VALUES ('101','ox_quiz');
INSERT INTO game(id,category) VALUES ('102','ox_quiz');
INSERT INTO game(id,category) VALUES ('103','ox_quiz');
INSERT INTO game(id,category) VALUES ('104','ox_quiz');
INSERT INTO game(id,category) VALUES ('105','ox_quiz');
INSERT INTO game(id,category) VALUES ('106','ox_quiz');
INSERT INTO game(id,category) VALUES ('107','ox_quiz');
INSERT INTO game(id,category) VALUES ('108','ox_quiz');
INSERT INTO game(id,category) VALUES ('109','ox_quiz');
INSERT INTO game(id,category) VALUES ('110','ox_quiz');
INSERT INTO game(id,category) VALUES ('111','ox_quiz');
INSERT INTO game(id,category) VALUES ('112','ox_quiz');
INSERT INTO game(id,category) VALUES ('113','ox_quiz');
INSERT INTO game(id,category) VALUES ('114','ox_quiz');
INSERT INTO game(id,category) VALUES ('115','ox_quiz');
INSERT INTO game(id,category) VALUES ('116','ox_quiz');
INSERT INTO game(id,category) VALUES ('117','ox_quiz');
INSERT INTO game(id,category) VALUES ('118','ox_quiz');
INSERT INTO game(id,category) VALUES ('119','ox_quiz');
INSERT INTO game(id,category) VALUES ('120','ox_quiz');

INSERT INTO ox_quiz(id,question,answer) VALUES (101, '딸기는 장미과에 속한다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (102, '동전 테두리에 있는 톱니는 시각장애인을 위해 고안되었다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (103, '뱀은 뒤로 갈 수 있다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (104, '빵은 순수한 우리말이다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (105, '새는 뒤로도 날 수 있다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (106, '오징어의 피는 푸르다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (107, '양파는 채소가 아니라 백합이다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (108, '일찍 자야 키가 큰다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (109, '지렁이도 눈이 있다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (110, '날계란 두개를 동시에 부딪히면 둘다 깨진다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (111, '매미의 애벌레는 굼벵이다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (112, '지문은 오직 사람에게만 있는 것이다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (113, '사람들이 많이 하는 하품은 전염된다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (114, '일산화탄소는 암의 원인이자 만병의 근원이다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (115, '손톱과 발톱은 피부가 변해서 된 것이다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (116, '배꼽의 때를 닦아내면 배가 아프다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (117, '물고기는 소변을 보지 않는다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (118, '개미도 63빌딩에서 떨어지면 죽는다.',false);
INSERT INTO ox_quiz(id,question,answer) VALUES (119, '개구리는 겨울잠을 자는 동안 숨을 쉬지 않는다.',true);
INSERT INTO ox_quiz(id,question,answer) VALUES (120, '달팽이는 턱이 없다.',true);

INSERT INTO game(id,category) VALUES ('201','quiz');
INSERT INTO game(id,category) VALUES ('202','quiz');
INSERT INTO game(id,category) VALUES ('203','quiz');
INSERT INTO game(id,category) VALUES ('204','quiz');
INSERT INTO game(id,category) VALUES ('205','quiz');
INSERT INTO game(id,category) VALUES ('206','quiz');
INSERT INTO game(id,category) VALUES ('207','quiz');
INSERT INTO game(id,category) VALUES ('208','quiz');
INSERT INTO game(id,category) VALUES ('209','quiz');
INSERT INTO game(id,category) VALUES ('210','quiz');
INSERT INTO game(id,category) VALUES ('211','quiz');
INSERT INTO game(id,category) VALUES ('212','quiz');
INSERT INTO game(id,category) VALUES ('213','quiz');
INSERT INTO game(id,category) VALUES ('214','quiz');
INSERT INTO game(id,category) VALUES ('215','quiz');
INSERT INTO game(id,category) VALUES ('216','quiz');
INSERT INTO game(id,category) VALUES ('217','quiz');
INSERT INTO game(id,category) VALUES ('218','quiz');
INSERT INTO game(id,category) VALUES ('219','quiz');
INSERT INTO game(id,category) VALUES ('220','quiz');

INSERT INTO quiz(id,question,answer) VALUES (201, '대한민국 최남단에 있는 섬은?','마라도');
INSERT INTO quiz(id,question,answer) VALUES (202, '제주도의 옛 이름은?','탐라');
INSERT INTO quiz(id,question,answer) VALUES (203, '"노인과 바다"를 쓴 작가는?','해밍웨이');
INSERT INTO quiz(id,question,answer) VALUES (204, '레오나르도 다빈치가 그린 "최후의 만찬"에서 예수를 포함하여 나오는 인물은 총 몇명일까요?','13명');
INSERT INTO quiz(id,question,answer) VALUES (205, '작은 변화가 폭풍우와 같은 커다란 변화로 유발시키는 현상을 말하는 이 용어는 무엇일까요?','나비효과');
INSERT INTO quiz(id,question,answer) VALUES (206, '독도 해역에 매장 된 자원이며, 메탄이 주성분인 가스가 얼음처럼 고체화된 에너지인 이 자원의 이름은 무엇일까요?','하이드레이트');
INSERT INTO quiz(id,question,answer) VALUES (207, '17세기 조선 숙종 때의 문신이자 소설가인 서포 "김만중"이 쓴 유명한 한글 소설인 이것은 무엇일까요?','구운몽');
INSERT INTO quiz(id,question,answer) VALUES (208, '조선 중기 임진왜란 때 의병장으로 주로 말을 타고 왜적을 무찔렀으며, 홍의장군이라고도 불린 이 인물은 누구일까요?','곽재우');
INSERT INTO quiz(id,question,answer) VALUES (209, '돼지의 "등겹살"이며 목심과 등심의 연결부위에 있는 사람 손바닥만한 오각형 모양의 살코기인 이 부위는?','가브리살');
INSERT INTO quiz(id,question,answer) VALUES (210, '빈모강에 속하는 환형동물의 총칭으로 철학자 아리스토텔레스는 이것을 "지구의 창자"라고 했습니다 이것은 무엇일까요?','지렁이');
INSERT INTO quiz(id,question,answer) VALUES (211, '용액의 산성, 염기성을 판단하는데 쓰이는 "종이의 이름"으로 산성은 붉은색, 염기성은 푸른색을 띠운다 이 종이의 이름은?','리트머스');
INSERT INTO quiz(id,question,answer) VALUES (212, '대한민국 6개 광역시를 다 말하시오.','대전, 대구, 부산, 인천, 광주, 울산');
INSERT INTO quiz(id,question,answer) VALUES (213, '중세 말기에 영국과 프랑스가 벌인 전쟁인 "백년 전쟁"은 몇 년간 치뤄진 전쟁일까요?','116년');
INSERT INTO quiz(id,question,answer) VALUES (214, '18세기 중엽 영국에서 시작된 기술혁신과 이에 수반하여 일어난 사회·경제 구조의 변혁을 무엇이라 할까요?','산업혁명');
INSERT INTO quiz(id,question,answer) VALUES (215, '그리스 신화에서 나오는 티탄족 이아페토스의 아들이며, "먼저 생각하는 사람"이라는 뜻의 이름인 이 인물은?','프로메테우스');
INSERT INTO quiz(id,question,answer) VALUES (216, '우리나라 최초의 한글 소설은?','홍길동전');
INSERT INTO quiz(id,question,answer) VALUES (217, '불로장생을 꿈 꿔 전 세계를 뒤져 불로초를 찾았던 왕의 이름은?','진시황');
INSERT INTO quiz(id,question,answer) VALUES (218, '색상대비를 이루는 한 쌍의 색상, 즉 반대되는 색상을 의미하는 단어는?','보색');
INSERT INTO quiz(id,question,answer) VALUES (219, '우리나라 국보 1호는?','숭례문');
INSERT INTO quiz(id,question,answer) VALUES (220, 'e-mail의 e는 무엇의 약자인가?','electronic');



INSERT INTO game(id,category) VALUES ('301','start_game');
INSERT INTO game(id,category) VALUES ('302','start_game');
INSERT INTO game(id,category) VALUES ('303','start_game');
INSERT INTO game(id,category) VALUES ('304','start_game');
INSERT INTO game(id,category) VALUES ('305','start_game');
INSERT INTO game(id,category) VALUES ('306','start_game');
INSERT INTO game(id,category) VALUES ('307','start_game');
INSERT INTO game(id,category) VALUES ('308','start_game');
INSERT INTO game(id,category) VALUES ('309','start_game');
INSERT INTO game(id,category) VALUES ('310','start_game');
INSERT INTO game(id,category) VALUES ('311','start_game');
INSERT INTO game(id,category) VALUES ('312','start_game');
INSERT INTO game(id,category) VALUES ('313','start_game');
INSERT INTO game(id,category) VALUES ('314','start_game');
INSERT INTO game(id,category) VALUES ('315','start_game');
INSERT INTO game(id,category) VALUES ('316','start_game');
INSERT INTO game(id,category) VALUES ('317','start_game');
INSERT INTO game(id,category) VALUES ('318','start_game');
INSERT INTO game(id,category) VALUES ('319','start_game');
INSERT INTO game(id,category) VALUES ('320','start_game');

INSERT INTO start_game(id,question,example) VALUES (301, 'ㄱㄱ','경기, 기계, 기구, 감기, 광고, 건강');
INSERT INTO start_game(id,question,example) VALUES (302, 'ㅇㅈ','여자, 여주, 이자, 이주, 의자, 인정');
INSERT INTO start_game(id,question,example) VALUES (303, 'ㅂㄷ','바다, 부대, 바둑, 배달, 바닥, 방도');
INSERT INTO start_game(id,question,example) VALUES (304, 'ㄴㅈ','남자, 내정, 누전, 날조, 누적, 나중');
INSERT INTO start_game(id,question,example) VALUES (305, 'ㄱㅇ','거울, 기원, 기우, 경우, 강연, 군인');
INSERT INTO start_game(id,question,example) VALUES (306, 'ㅅㅂ','신발, 수박, 선비, 소비, 소박, 시비');
INSERT INTO start_game(id,question,example) VALUES (307, 'ㅂㅅ','박수, 방수, 변수, 비수, 분식, 발상');
INSERT INTO start_game(id,question,example) VALUES (308, 'ㅇㅇ','여우, 염원, 이유, 아연, 우유, 아이');
INSERT INTO start_game(id,question,example) VALUES (309, 'ㄱㅁ','기모, 강물, 가면, 가망, 기만, 교만');
INSERT INTO start_game(id,question,example) VALUES (310, 'ㅎㅈ','한지, 휴지, 현재, 휴전, 현장, 하중');
INSERT INTO start_game(id,question,example) VALUES (311, 'ㅈㄹ','중력, 장로, 진루, 전래, 전령, 지리');
INSERT INTO start_game(id,question,example) VALUES (312, 'ㅁㅈ','모자, 명주, 메주, 밀정, 먹지, 매정');
INSERT INTO start_game(id,question,example) VALUES (313, 'ㄱㄷ','강당, 강도, 건달, 기대, 기둥, 계단');
INSERT INTO start_game(id,question,example) VALUES (314, 'ㄷㄷ','도둑, 당도, 도달, 다도, 단도, 대답');
INSERT INTO start_game(id,question,example) VALUES (315, 'ㅅㄱ','성공, 상가, 산골, 삭감, 상경, 성경');
INSERT INTO start_game(id,question,example) VALUES (316, 'ㅊㅅ','책상, 취소, 창살, 청소, 찬사, 취사');
INSERT INTO start_game(id,question,example) VALUES (317, 'ㅎㅅ','향수, 헌신, 회수, 해수, 해소, 함수');
INSERT INTO start_game(id,question,example) VALUES (318, 'ㅅㅎ','소화, 산화, 산호, 선호, 상호, 수화');
INSERT INTO start_game(id,question,example) VALUES (319, 'ㅂㅁ','보물, 비명, 박멸, 비밀, 빈민, 병마');
INSERT INTO start_game(id,question,example) VALUES (320, 'ㅅㄹ','사랑, 실리, 서랍, 선로, 선례, 신랑');


INSERT INTO with_one_mouth(id,words1,words2) VALUES (401,'피자','치킨');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (402,'짜장','짬뽕');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (403,'민초단','반민초단');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (404,'후라이드','양념');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (405,'물만두','군만두');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (406,'콜라','사이다');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (407,'산','바다');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (408,'소고기','돼지고기');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (409,'갤럭시','아이폰');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (410,'부먹','찍먹');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (411,'우동','냉모밀');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (412,'물냉','비냉');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (413,'삼성','LG');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (414,'순살치킨','뼈치킨');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (415,'참치김치찌개','돼지김치찌개');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (416,'팥붕어빵','슈크림붕어빵');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (417,'간장게장','양념게장');
INSERT INTO with_one_mouth(id,words1,words2) VALUES (418,'강아지','고양이');

INSERT INTO communication(id, category, question) VALUES (1,'나','당신이 가장 좋아하는 음악은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (2,'나','당신은 다른사람에게 어떤 사람인 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (3,'나','당신은 다른사람에게 어떤 사람인 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (4,'나','당신이 가장 사랑하는 사람은 누구인가요?');
INSERT INTO communication(id, category, question) VALUES (5,'나','당신이 해본 가장 큰 일탈은?');
INSERT INTO communication(id, category, question) VALUES (6,'나','스스로 생각하는 본인의 콤플렉스는?');
INSERT INTO communication(id, category, question) VALUES (7,'나','가장 자신 있는 신체부위는?');
INSERT INTO communication(id, category, question) VALUES (8,'나','좋아하는 영화 장르는?');
INSERT INTO communication(id, category, question) VALUES (9,'나','가장 좋아하는 계절과 그 이유는?');
INSERT INTO communication(id, category, question) VALUES (10,'나','좋아하는 연예인이 있나요? 있다면 누구인가요?');
INSERT INTO communication(id, category, question) VALUES (11,'나','살면서 꼭 해보고 싶은 일이 있다면 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (12,'나','인생에서 가장 행복했던 순간이 있다면?');
INSERT INTO communication(id, category, question) VALUES (13,'나','당신의 가장 친한 사람을 소개해주세요!');
INSERT INTO communication(id, category, question) VALUES (14,'나','당신의 이상형은?');
INSERT INTO communication(id, category, question) VALUES (15,'나','가장 인상깊게 읽은 책은?');
INSERT INTO communication(id, category, question) VALUES (16,'나','스스로에 대해 30초 이내로 소개해주세요!');
INSERT INTO communication(id, category, question) VALUES (17,'나','학창시절 별명이 있다면?');
INSERT INTO communication(id, category, question) VALUES (18,'나','주로 보는 유튜브 채널이 있다면?');
INSERT INTO communication(id, category, question) VALUES (19,'나','키우는 혹은 키우고 싶은 애완동물이 있나요?');
INSERT INTO communication(id, category, question) VALUES (20,'나','남이 보는 당신의 첫인상은 주로 어떤가요?');

INSERT INTO communication(id, category, question) VALUES (101,'가치','일과 사랑 중에 골라야한다면 당신은 어떤 것을 고를 건가요?');
INSERT INTO communication(id, category, question) VALUES (102,'가치','돈과 명예 중에 당신이 중시하는 건 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (103,'가치','살면서 했던 일 중에 가장 가치 있었던 일을 꼽는다면?');
INSERT INTO communication(id, category, question) VALUES (104,'가치','당신이 한 소비 중에 가장 가치 있는 소비가 있다면?');
INSERT INTO communication(id, category, question) VALUES (105,'가치','재능기부에 대한 당신의 생각은 어떤가요?');
INSERT INTO communication(id, category, question) VALUES (106,'가치','당신은 남녀사이에 친구가 가능하다고 생각하나요?');
INSERT INTO communication(id, category, question) VALUES (107,'가치','여행할 때, 당신은 맛집과 볼 거리 중 어느 것을 더 중요하게 여기나요?');
INSERT INTO communication(id, category, question) VALUES (108,'가치','오늘이 인생의 마지막 날이라면, 어떤 하루를 보낼 것인가요?');
INSERT INTO communication(id, category, question) VALUES (109,'가치','당신의 행복을 위해 꼭 필요한 것이 있다면?');
INSERT INTO communication(id, category, question) VALUES (110,'가치','오늘 쓰는 모든 돈이 공짜라면 무엇을 할 건가요? (부동산, 금융 상품 금지)');
INSERT INTO communication(id, category, question) VALUES (111,'가치','가장 좋아하는 말귀나 노래 가사가 있나요?');
INSERT INTO communication(id, category, question) VALUES (112,'가치','당신의 묘비명을 남길 수 있다면, 어떤 말을 남기고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (113,'가치','사람을 만날 때 가장 중요하게 여기는 가치는?');

INSERT INTO communication(id, category, question) VALUES (201,'가족','당신은 가족에서 어떤 역할을 담당하고 있나요?');
INSERT INTO communication(id, category, question) VALUES (202,'가족','당신이 가족에게 바라는 점이 있다면 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (203,'가족','당신이 가족을 만든다면, 어떤 가정을 꾸리고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (204,'가족','가족의 말 중에 가장 상처가 됐던 말이 있나요?');
INSERT INTO communication(id, category, question) VALUES (205,'가족','당신 가족의 장점을 꼽자면?');
INSERT INTO communication(id, category, question) VALUES (206,'가족','가족에게 감사했던 순간은?');
INSERT INTO communication(id, category, question) VALUES (207,'가족','가족 구성원에 대해 간단히 소개해주세요!');
INSERT INTO communication(id, category, question) VALUES (208,'가족','당신에게 가족은 어떤 존재인가요?');
INSERT INTO communication(id, category, question) VALUES (209,'가족','가족에게 아쉬운 점이 있다면?');
INSERT INTO communication(id, category, question) VALUES (210,'가족','가족에 대한 현재 당신의 마음은 어떤가요?');
INSERT INTO communication(id, category, question) VALUES (211,'가족','가족 구성원의 역할을 선택할 수 있다면, 어떤 역할을 맡고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (212,'가족','당신의 가족과 다른 사람들의 가족과 차이점이 있다면?');
INSERT INTO communication(id, category, question) VALUES (213,'가족','당신이 가장 잘하는 집안일은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (214,'가족','당신은 가족들과 주로 어떤 시간을 보내나요?');
INSERT INTO communication(id, category, question) VALUES (215,'가족','가족들에게 충분한 돈과 시간이 주어진다면 무엇을 하고 싶나요?');

INSERT INTO communication(id, category, question) VALUES (301,'상상','당신이 대통령이라면, 가장 먼저 하고 싶은 것이 있나요?');
INSERT INTO communication(id, category, question) VALUES (302,'상상','당신이 해본 상상 중 가장 창의적인 것은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (303,'상상','당신이 로또 1등 당첨자라면, 상금을 어떻게 사용할 것인가요?');
INSERT INTO communication(id, category, question) VALUES (304,'상상','당신이 다시 태어날 수 있다면, 어떤 사람으로 태어나고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (305,'상상','게임/만화 속 캐릭터가 될 수 있다면, 가장 탐나는 캐릭터는?');
INSERT INTO communication(id, category, question) VALUES (306,'상상','요술 램프가 당신의 것이라면, 당신의 소원 3가지는?');
INSERT INTO communication(id, category, question) VALUES (307,'상상','무인도에 3가지만 가지고 갈 수 있다면?');
INSERT INTO communication(id, category, question) VALUES (308,'상상','하루만 원하는 몸으로 바꿀 수 있다면, 누구와 바꾸고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (309,'상상','어떤 직업을 선택하든 우수한 실무 능력을 갖출 수 있다면, 당신은 어떤 직업을 갖고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (310,'상상','당신에게 어디든 갈 수 있는 문이 있다면, 어디로 가고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (311,'상상','당신에게 초능력이 있다면, 어떤 능력을 가지고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (312,'상상','당신이 사물이 된다면, 어떤 사물이 되고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (313,'상상','당신이 국적을 정해서 태어날 수 있다면, 어느 나라에서 태어나고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (314,'상상','딱 한 번 시간을 되돌아 갈 수 있는 버튼을 누를 수 있다면, 언제로 돌아가고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (315,'상상','재능을 한 가지 얻을 수 있다면, 어떤 재능이 갖고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (316,'상상','멧돼지나 곰을 만나면 당신은 어떻게 할 것인가요?');
INSERT INTO communication(id, category, question) VALUES (317,'상상','유튜버가 된다면 어떤 콘텐츠를 운영하고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (318,'상상','당신에게 강연을 위한 15분의 시간이 주어지고 모든 관객이 경청하는 상황이라면, 어떤 강연을 하고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (319,'상상','내가 이름을 다시 정할 수 있다면, 어떤 이름으로 살고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (320,'상상','지금 타임캡슐을 묻는다면, 어떤 것을 넣고 싶나요?');

INSERT INTO communication(id, category, question) VALUES (401,'일상','당신은 평소 무엇을 하며 휴식을 취하나요?');
INSERT INTO communication(id, category, question) VALUES (402,'일상','당신은 어떤 상황에서 제일 분노를 느끼나요?');
INSERT INTO communication(id, category, question) VALUES (403,'일상','당신은 주로 어떤 것을 할 때 기분이 좋나요?');
INSERT INTO communication(id, category, question) VALUES (404,'일상','당신이 평소 즐겨먹는 음식은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (405,'일상','핸드폰에서 가장 많이 사용하는 앱은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (406,'일상','주로 많이 하는 지출은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (407,'일상','당신은 현재의 스스로에게 만족하나요?');
INSERT INTO communication(id, category, question) VALUES (408,'일상','실내에서 쉬는 것이 힐링인가요? 야외에서 활동하는 것이 힐링인가요?');
INSERT INTO communication(id, category, question) VALUES (409,'일상','오늘 일기를 쓴다면, 어떤 말을 적을 것인가요?');
INSERT INTO communication(id, category, question) VALUES (410,'일상','더 나은 내가 되기 위해서 어떤 노력을 하고 있나요?');

INSERT INTO communication(id, category, question) VALUES (501,'과거','당신은 학창시절 어떤 학생이었나요?');
INSERT INTO communication(id, category, question) VALUES (502,'과거','당신의 어린시절 꿈은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (503,'과거','당신이 후회하는 순간을 꼽자면?');
INSERT INTO communication(id, category, question) VALUES (504,'과거','살면서 들은 가장 좋은 말은?');
INSERT INTO communication(id, category, question) VALUES (505,'과거','어린시절 가장 인상깊게 본 만화는?');
INSERT INTO communication(id, category, question) VALUES (506,'과거','지금까지 살아오면서 전성기가 있었다면 언제 인 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (507,'과거','당신이 상처 준 사람이 있나요?');
INSERT INTO communication(id, category, question) VALUES (508,'과거','당신이 위로가 돼 준 사람이 있나요?');
INSERT INTO communication(id, category, question) VALUES (509,'과거','지나온 삶을 되돌아 봤을 때, 잘 살아온 것 같나요?');

INSERT INTO communication(id, category, question) VALUES (601,'미래','당신이 미래에 가장 하고 싶은 것은 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (602,'미래','당신은 미래에 어떤 삶을 살고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (603,'미래','10년 후의 나는 어떤 삶을 살고 있을 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (604,'미래','어떤 것이 나를 더 행복하게 만들어 줄 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (605,'미래','당신은 미래에 어떤 일을 하며 살고 있을 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (606,'미래','당신에게 인생의 전성기가 온다면, 언제 일 것 같나요?');
INSERT INTO communication(id, category, question) VALUES (607,'미래','당신의 마지막 순간에 누가 함께 있길 바라나요?');
INSERT INTO communication(id, category, question) VALUES (608,'미래','당신이 해보고 싶은 취미는 무엇인가요?');
INSERT INTO communication(id, category, question) VALUES (609,'미래','미래에 개발됐으면 하는 제품/서비스가 있나요?');


INSERT INTO communication(id, category, question) VALUES (701,'관계','당신은 다른 사람에게 어떤 사람이고 싶나요?');
INSERT INTO communication(id, category, question) VALUES (702,'관계','당신이 소중하게 여기는 관계는 어떤 관계인가요?');
INSERT INTO communication(id, category, question) VALUES (703,'관계','당신이 관계를 맺기 위해 하는 노력이 있나요?');
INSERT INTO communication(id, category, question) VALUES (704,'관계','당신이 친해지는 사람들의 공통점이 있다면?');
INSERT INTO communication(id, category, question) VALUES (705,'관계','당신의 가장 친한 친구에 대해 자랑해주세요!');
INSERT INTO communication(id, category, question) VALUES (706,'관계','당신은 주로 갈등상황이 발생하면 어떻게 푸나요?');
INSERT INTO communication(id, category, question) VALUES (707,'관계','가까웠지만 완전히 끝을 낸 관계가 있나요?');
INSERT INTO communication(id, category, question) VALUES (708,'관계','당신이 피하는 관계가 있다면 어떤 이유인가요?');
INSERT INTO communication(id, category, question) VALUES (709,'관계','당신과 친해지기 위해서 해야 할 노력이 있다면?');
INSERT INTO communication(id, category, question) VALUES (710,'관계','연인관계에서 가장 많이 보는 것은?');
INSERT INTO communication(id, category, question) VALUES (711,'관계','당신과 관계 유지를 위해 어떤 것이 필요할까요?');










