INSERT INTO game(id,category) VALUES ('1','balance');
INSERT INTO game(id,category) VALUES ('2','balance');
INSERT INTO game(id,category) VALUES ('3','balance');
INSERT INTO game(id,category) VALUES ('4','balance');
INSERT INTO game(id,category) VALUES ('5','balance');
INSERT INTO game(id,category) VALUES ('6','balance');
INSERT INTO game(id,category) VALUES ('7','balance');
INSERT INTO game(id,category) VALUES ('8','balance');
INSERT INTO game(id,category) VALUES ('9','balance');
INSERT INTO game(id,category) VALUES ('10','balance');
INSERT INTO game(id,category) VALUES ('11','balance');
INSERT INTO game(id,category) VALUES ('12','balance');
INSERT INTO game(id,category) VALUES ('13','balance');
INSERT INTO game(id,category) VALUES ('14','balance');
INSERT INTO game(id,category) VALUES ('15','balance');
INSERT INTO game(id,category) VALUES ('16','balance');
INSERT INTO game(id,category) VALUES ('17','balance');
INSERT INTO game(id,category) VALUES ('18','balance');
INSERT INTO game(id,category) VALUES ('19','balance');

INSERT INTO balance_game(id,solution1,solution2) VALUES (1, '오이케이크 먹기', '김치케이크 먹기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (2, '평생 양치 안하기', '평생 샤워 안하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (3, '요플레 뚜껑 그냥 버리기', '쭈쭈바 꼬다리 그냥 버리기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (4, '365일 폭염', '365일 장마');
INSERT INTO balance_game(id,solution1,solution2) VALUES (5, '평생동안 키 100cm', '평생동안 몸무게 100kg');
INSERT INTO balance_game(id,solution1,solution2) VALUES (6, '100%확률로 500만원', '1/5확률로 100억');
INSERT INTO balance_game(id,solution1,solution2) VALUES (7, '평생 두통', '평생 치통');
INSERT INTO balance_game(id,solution1,solution2) VALUES (8, '온 세상 사람들이 나한테만 말하기', '온 세상 사람들이 나한테 말 안 걸고 내가 말해도 못 듣기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (9, '절친이 애인 새우 까주기', '애인이 절친 새우 까주기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (10, '내가 10억 받고 원수는 100억 받기', '그냥 둘 다 아무것도 안 받기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (11, '내 인터넷 기록 공개하기', '내 카톡, DM기록 공개하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (12, '원하는 음식 평생 무료로 제공받기', '원하는 옷 평생 무료로 제공받기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (13, '언제 죽을지 알기', '어떻게 죽을지 알기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (14, '하루 종일 입 다물고 있기', '하루 종일 말하고 다니기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (15, '300억 받고 모든 인간관계 정리하기', '그냥 살기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (16, '평생 고기 끊기', '평생 밀가루 끊기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (17, '자도 자도 피곤히기', '먹어도 먹어도 배고프기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (18, '마마보이/마마걸이랑 결혼하기', '바람둥이랑 결혼하기');
INSERT INTO balance_game(id,solution1,solution2) VALUES (19, '이국종 교수한테 맞고 추성훈한테 수술 받기', '추성훈한테 맞고 이국종 교수한테 수술 받기');

